version: '3.8'

services:
    db_service:
        container_name: db_container
        image: postgres:latest
        env_file:
            - .env.db
        ports:
            - 5432:5432

    app_service:
        container_name: gsteam_container
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - 8001:8000
        depends_on:
            - db_service