"""From item model unnecessary relationships was removed

Revision ID: 19bdba5e3569
Revises: 128ac3ec5f83
Create Date: 2024-06-12 07:05:05.299588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bdba5e3569'
down_revision = '128ac3ec5f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_tag_rel')
    op.drop_table('item_platform_rel')
    op.drop_table('platform')
    op.drop_table('tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('tag_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tag_pkey'),
    sa.UniqueConstraint('name', name='tag_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('platform',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('platform_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('vendor', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='platform_pkey'),
    sa.UniqueConstraint('name', name='platform_name_key'),
    sa.UniqueConstraint('vendor', name='platform_vendor_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('item_platform_rel',
    sa.Column('item_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('platform_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='item_platform_rel_item_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name='item_platform_rel_platform_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'platform_id', name='item_platform_rel_pkey')
    )
    op.create_table('item_tag_rel',
    sa.Column('item_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='item_tag_rel_item_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='item_tag_rel_tag_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id', name='item_tag_rel_pkey')
    )
    # ### end Alembic commands ###
