"""consumer renamed to user with editions

Revision ID: b24cfd1c0d30
Revises: f149e03cbcc6
Create Date: 2024-06-14 17:13:48.206925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24cfd1c0d30'
down_revision = 'f149e03cbcc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.BigInteger(), nullable=True))
        batch_op.drop_constraint('cart_consumer_id_fkey',  type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('consumer_id')
    op.drop_table('consumer_model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumer_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_consumer_id_fkey', 'consumer_model', ['consumer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('user_id')

    op.create_table('consumer_model',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('profile_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='consumer_model_pkey'),
    sa.UniqueConstraint('profile_name', name='consumer_model_profile_name_key')
    )
    # ### end Alembic commands ###
